### ISSUE TITLE
stampzilla cli enhancements

### ISSUE THREAD

**Issue by jonaz** [stampzilla/stampzilla-go#51]
I think we should do those modifications. What do you think @stamp ?
- [x] Publish binaries on github and download them instead of using go get
- [x] Publish the SHA1 hashes on github in someway so downloader can verify.
- [x] Generate systemd services for all nodes (keep nohup as an alternative on systems without systemd)
- [x] stampzilla start/stop etc should call systemctl if system support systemd
- [x] logging should go to the systemd journal and stampzilla log should use that if system supports systemd. This we get for free in systemd. Only need to make sure we read logs from correct place when calling stampzilla log.
- [x] add stampzilla version command which queries all installed binaries with -version flag? (this flag need to be implemented in all nodes)
- [x] generate logrotate config in stampzilla cli

The systemd approach must also implement using systemd for enable disable autostart. For example stampzilla restart should only restart those services active/enabled in systemd. 
This way /etc/stampzilla/nodes.conf is not needed on a systemd system.

**Comment by stamp** [comment]
Sounds like great ideas!

I think we should do all of them. I have some more ideas but they are enhancements in other areas of stampzilla aswell..

- [ ] Add node version number to node registration data (so that it will be sent to the server)
- [ ] Breakout all nodes to separate repositories and make one common that they all depend on that contains the prototol
- [ ] Poll, compare and show information about latest version for each node in both cli and webgui. 
- [ ] Build the updater node as a stampzilla node so you can see status and control it from webgui
